name: Trigger UpdateVersions Action in other Repo

on:
  workflow_dispatch:
    inputs:
      image-version: 
        description: "Version to set app-version to"
        required: true
      path-to-chart-yaml:
        description: "Path to Chart.yaml"
        required: true
        default: Chart.yaml
      path-to-backend-chart:
        description: "Path to backend Chart.yaml"
        required: true
        default: charts/backend/Chart.yaml
      path-to-frontend-chart:
        description: "Path to frontend Chart.yaml"
        required: true
        default: charts/frontend/Chart.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call GitHub API to Trigger UpdateVersions Action
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_2_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"event_type": "trigger-event", "client_payload": {"image-version": "${{ inputs.image-version }}", "path-to-chart-yaml": "${{ inputs.path-to-chart-yaml }}", "path-to-backend-chart": "${{ inputs.path-to-backend-chart }}", "path-to-frontend-chart": "${{ inputs.path-to-frontend-chart }}"}}' \
          "https://api.github.com/repos/jan-niklasml/playground/dispatches"
