name: Trigger UpdateVersions Action in other Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger UpdateVersions Action
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.REPO_2_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/jan-niklasml/playground/dispatches \
          -d '{"event_type": "trigger-event"}'
