name: Trigger UpdateVersions Action in other Repo

on:
  workflow_dispatch:
    inputs:
      app-version: 
        description: "New App-Version"
        required: true
      path-to-chart-yaml:
        description: "Path to Chart.yaml"
        required: true
env:
  REPO_2_TOKEN: ${{ secrets.REPO_2_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call GitHub API to Trigger UpdateVersions Action
        run: |
          echo "${REPO_2_TOKEN}" | gh auth login --with-token
          gh workflow run updateVersions.yml --ref jan-niklasml-patch-2 -f app-version=${{ inputs.app-version }} -f path-to-chart-yaml=${{ inputs.path-to-chart-yaml }} \
          --repo jan-niklasml/playground
