name: Trigger UpdateVersions Action in other Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call GitHub API to Trigger UpdateVersions Action
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_2_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"event_type": "trigger-event", "client_payload": {"image-version": "1.2.3"}}' \
          "https://api.github.com/repos/jan-niklasml/playground/dispatches"
