name: Trigger UpdateVersions Action in other Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger UpdateVersions Action
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_2_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"ref":"main"}' \
          "https://api.github.com/repos/jan-niklasml/playground/.github/workflows/updateVersions.yml/dispatches"
